-- Ejecutar una sola vez en Supabase SQL Editor

alter table public.clientes
add column if not exists afiliado boolean default false,
add column if not exists requiere_factura boolean default false,
add column if not exists razon_social text,
add column if not exists cuit text,
add column if not exists direccion_fiscal text,
add column if not exists tipo_factura text,
add column if not exists condicion_iva text,
add column if not exists updated_at timestamptz default now();

create unique index if not exists clientes_dni_unique
on public.clientes (dni)
where dni is not null;

create table if not exists public.tarifas (
  id bigint generated by default as identity primary key,
  tipo_usuario text not null unique
    check (tipo_usuario in ('AFILIADO','NO_AFILIADO')),
  valor_hora numeric(12,2) not null,
  activo boolean default true,
  updated_at timestamptz default now()
);

insert into public.tarifas (tipo_usuario, valor_hora)
values ('AFILIADO',65000),('NO_AFILIADO',99500)
on conflict (tipo_usuario) do update
set valor_hora=excluded.valor_hora, activo=true, updated_at=now();

alter table public.tarifas enable row level security;

drop policy if exists "Usuarios autenticados ven tarifas" on public.tarifas;
create policy "Usuarios autenticados ven tarifas"
on public.tarifas for select to authenticated
using (activo = true);

alter table public.reservas
add column if not exists tipo_usuario text
  check (tipo_usuario in ('AFILIADO','NO_AFILIADO')),
add column if not exists cantidad_horas numeric(6,2),
add column if not exists valor_hora numeric(12,2);
